blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    
    path('blogs/',views.BlogListView.as_view(),name='blogs'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(),name='blog-detail'),
    path('blog/create/', views.BlogCreate.as_view(), name='blog-create'),
    path('blog/<int:pk>/update', views.BlogUpdate.as_view(), name='blog-update'),
    path('blog/<int:pk>/delete', views.BlogDelete.as_view(), name='blog-delete'),
    
    path('blog/<int:pk>/comment/', views.CommentCreate.as_view(), name='blog-comment'),

    path('bloggers/',views.BloggerListView.as_view(),name='bloggers'),
    path('blogger/<int:pk>', views.BloggerDetailView.as_view(),name='blogger-detail'),
    path('blogger/<int:pk>/myblogs', views.BlogListbyAuthorView.as_view(),name='blogger-myblog'),
    path('blogger/signup/', views.BloggerSignup, name='blogger-signup'),
    path('blogger/<int:pk>/update/', views.BloggerUpdate.as_view(), name='blogger-update'),
    
]

miniblog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('blog/', include('blog.urls')),
]

#Add URL maps to redirect the base URL to our application
urlpatterns += [
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    time_of_creation = models.DateTimeField(default=datetime.now, null=True,blank=True)
    content = models.TextField(max_length=5000)

    class Meta:
        ordering = ['-time_of_creation']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog-detail', args=[str(self.id)])

class Blogger(models.Model):
    user = models.OneToOneField(User,on_delete=models.SET_NULL,null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    self_introduction = models.TextField(max_length=500)

    class Meta:
        ordering = ['user']

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('blogger-detail', args=[str(self.id)])

class Comment(models.Model):
    blog = models.ForeignKey('Blog', on_delete=models.SET_NULL,null=True)
    commenter = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    time_of_creation = models.DateTimeField(default=datetime.now,null=True,blank=True)
    content = models.TextField(max_length=500)

    class Meta:
        ordering = ['-time_of_creation']
    
    def __str__(self):
        return f'{self.commenter.username}@{self.time_of_creation} - {self.content[:75]}'
    
    def get_absolute_url(self):
        return reverse('comment-detail', args=[str(self.id)])

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
 
class BloggerSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name')

blog/views.py
from blog.models import Blogger
from django.shortcuts import redirect, render
from .models import Blog,Blogger,Comment
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from .forms import BloggerSignUpForm

# Create your views here.
def index(request):
    num_bloggers = Blogger.objects.all().count
    num_blogs = Blog.objects.all().count
    num_comments = Comment.objects.all().count

    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_bloggers': num_bloggers,
        'num_blogs':num_blogs,
        'num_comments':num_comments,
        'num_visits':num_visits,
    }

    return render(request,'index.html',context=context)


class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5

class BlogDetailView(generic.DetailView):
    model = Blog

class BloggerListView(generic.ListView):
    model = Blogger
    paginate_by = 5

class BloggerDetailView(generic.DetailView):
    model = Blogger

class BlogCreate(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ['title', 'time_of_creation', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class BlogUpdate(LoginRequiredMixin,UpdateView):
    model = Blog
    fields = ['title', 'content']

class BlogDelete(LoginRequiredMixin,DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs')

def BloggerSignup(request):
    if request.method == 'POST':
        form = BloggerSignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            Blogger.objects.update_or_create(user=user, first_name=user.first_name, last_name=user.last_name)
            user.save()
            user.blogger.save()
            return redirect('login')
    
    else:
        form = BloggerSignUpForm()
    
    context = {
        'form':form,
    }
    return render(request, 'signup.html', context)

class BloggerUpdate(LoginRequiredMixin, UpdateView):
    model = Blogger
    fields = ['first_name', 'last_name', 'self_introduction']

class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['time_of_creation', 'content']

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(CommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blog'] = get_object_or_404(Blog, pk = self.kwargs['pk'])
        return context
        
    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.commenter = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blog=get_object_or_404(Blog, pk = self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super().form_valid(form)

    def get_success_url(self): 
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'],})

class BlogListbyAuthorView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view for a list of blogs posted by a particular BlogAuthor.
    """
    model = Blog
    paginate_by = 5
    template_name ='blog/blog_list_by_author.html'
    
    def get_queryset(self):
        """
        Return list of Blog objects created by BlogAuthor (author id specified in URL)
        """
        id = self.kwargs['pk']
        target_author=get_object_or_404(Blogger, pk = id)
        return Blog.objects.filter(author=target_author.user)
        
    def get_context_data(self, **kwargs):
        """
        Add BlogAuthor to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(BlogListbyAuthorView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['blogger'] = get_object_or_404(Blogger, pk = self.kwargs['pk'])
        return context

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}<title>Mini Blog</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"">
        <!--add additional css in static file-->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>

    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'blogs' %}">All Blogs</a></li>
                        <li><a href="{% url 'bloggers' %}">All Bloggers</a></li>
                        <li><a href="{% url 'blog-create' %}">New Blog</a></li>

                        {% if user.is_authenticated and user.blogger %}
                            <li>User: {{ user.get_username }}</li>
                            <li><a href="{% url 'blogger-detail' user.blogger.id %}">profile</a></li>
                            <li><a href="{% url 'blogger-myblog' user.blogger.id %}">My Blogs</a></li>
                            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                            <li><a href="{% url 'blogger-signup'%}">Signup</a></li>
                        {% endif %} 
                    </ul>
                    {% endblock %}
                </div>
                <div class="col-sm-10">{% block content %}{% endblock %}
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                    {% endif %}
                                    <span class="page-current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Blog</h1>
<p>Are you sure you want to delete the blog: {{ blog }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ blog.title }}</h1>

    <p><strong>Author:</strong> <a href="{{blog.author.blogger.get_absolute_url}}">{{ blog.author }}</a></p>
    <p><strong>Created at:</strong> {{ blog.time_of_creation }}</p>
    <p><strong>Content:</strong> {{ blog.content }}</p>

    {% if user.is_authenticated and user.username == blog.author.username %}
        <a href="{% url 'blog-update' blog.id %}">Edit This Blog</a></p>
        <a href="{% url 'blog-delete' blog.id %}">Delete This Blog</a></p>
    {% endif %}

    <div style="margin-left: 20px; margin-top: 20px;">
        <h4>Comments</h4>

        {% for comment in blog.comment_set.all %}
            <hr>
            <p>{{ comment }}</p>
        {% endfor %}

        {% if user.is_authenticated %}
            <a href="{% url 'blog-comment' blog.id %}">Add a new comment</a></p>
        {% else %}
            <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
        {% endif %} 

    
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blog List</h1>
    {% if blog_list %}
    <ul>
        {% for blog in blog_list %}
            <li>
                <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{ blog.time_of_creation}})  <a href="{{ blog.author.blogger.get_absolute_url }}">{{ blog.author}}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>there are no blogs</p>
    {% endif %}
{% endblock %}

blog/templates/blog/blog_list_by_author.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger: {{blogger}}</h1>
    
    {% if blog_list %}
    <h3>My Blog list</h3>
    <ul>
      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{blog.time_of_creation}})</a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>This blogger hasn't posted anything yet.</p>
    {% endif %}       
{% endblock %}

blog/templates/blog/blogger_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger: {{ blogger }}</h1>

    <p>Name: {{blogger.first_name}}, {{blogger.last_name}}</p>
    <p>Bio: {{blogger.self_introduction}}</p>

    {% if user.is_authenticated and user.username == blogger.user.username %}
        <a href="{% url 'blogger-update' blogger.id %}">update profile</a></p>
    {% endif %}


    <div style="margin-left: 20px; margin-top: 20px;">
        <h4>Posts</h4>

        <dl>
            {% for blog in blogger.user.blog_set.all %}
            <dt><a href="{{blog.get_absolute_url}}">{{blog}}</a>({{blog.time_of_creation}})</dt>
            {% endfor %}
        </dl>
    </div>
{% endblock %}

blog/templates/blog/blogger_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blog/templates/blog/blogger_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger List</h1>
    {% if blogger_list %}
    <ul>
        {% for blogger in blogger_list %}
            <li>
                <a href="{{ blogger.get_absolute_url }}">{{ blogger.user }}</a> 
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>there are no bloggers</p>
    {% endif %}
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "base_generic.html" %}

{% block content %}

<p>Post your comment for: <a href="{% url 'blog-detail' blog.pk %}">{{blog.title}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
    <title>Mini Blog Homepage</title>
{% endblock %}

{% block content %}
    <h1>Mini Blog Home</h1>
    <p>Welcome to Mini Blog</p>
    <h2>Dynamic content</h2>
    <p>The blog has the following record counts:</p>
    <ul>
        <li><strong>Blogs:</strong> {{ num_blogs }}</li>
        <li><strong>Comments:</strong> {{ num_comments }}</li>
        <li><strong>Bloggers:</strong> {{ num_bloggers }}</li>
        <li><strong>Visits:</strong> {{ num_visits }}</li>
    </ul>
{% endblock %}

blog/templates/signup.html
{% extends "base_generic.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
{% endblock %}